# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       speex
Summary:    A voice compression format (codec)
Version:    1.2~rc1
Release:    1
Group:      System/Libraries
License:    BSD
URL:        http://www.speex.org/
Source0:    http://downloads.xiph.org/releases/speex/%{name}-1.2rc1.tar.gz
Source100:  speex.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(ogg)


%description
Speex is a patent-free compression format designed especially for
speech. It is specialized for voice communications at low bit-rates in
the 2-45 kbps range. Possible applications include Voice over IP
(VoIP), Internet audio streaming, audio books, and archiving of speech
data (e.g. voice mail).



%package tools
Summary:    The tools package for %{name}
Group:      Applications/Multimedia
Requires:   %{name} = %{version}-%{release}

%description tools
Speex is a patent-free compression format designed especially for
speech. This package contains tools files and user's manual for %{name}.


%package devel
Summary:    Development package for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Speex is a patent-free compression format designed especially for
speech. This package contains development files for %{name}



%prep
%setup -q -n %{name}-1.2rc1

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -f $RPM_BUILD_ROOT%{_docdir}/speex/manual.pdf
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig








%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING TODO
%{_libdir}/libspeex*.so.*
# << files


%files tools
%defattr(-,root,root,-)
# >> files tools
%{_bindir}/speexenc
%{_bindir}/speexdec
%doc %{_mandir}/man1/speexenc.1*
%doc %{_mandir}/man1/speexdec.1*
# << files tools

%files devel
%defattr(-,root,root,-)
# >> files devel
%doc doc/manual.pdf
%{_includedir}/speex
%{_datadir}/aclocal/speex.m4
%{_libdir}/pkgconfig/speex*.pc
%{_libdir}/libspeex*.so
# << files devel

